name: HoverChat
version: $version
main: com.yxxngtai.hoverchat.HoverChatPlugin
api-version: 1.21.5
author: yxxngtai
contributor: Strokkur24

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
  
permissions:
  hoverchat.command:
    description: Permission for /hoverchat
    default: op